spring.datasource:
  url: jdbc:postgresql://localhost:54322/demo_dev?currentSchema=doggy
  username: test
  password: test

server.tomcat:
  threads:
    min-spare: 1

logging.level:
  app: debug
  jooq: info

app.auth.jwt:
  signerKeyId: es1
  keys:
    - id: es1
      algorithm: ES256
      verifier-key: |-
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEPenzh8Etl9tTxotn4IDPjc2ffjt9tIceCvQz0C6cFn62KgwyXCsSeYQeXguGiFHzqFqHj4h8ONmcHQHV777zzw==
      signer-key: |-
        MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCB5XLMrM7d/ENFbirI1rQV81oPgSlPHVCe8CcsFskXVSg==
