server.port: ${SERVER_PORT:8082}

spring:
  profiles.active: local-dev
  application:
    name: febit-boot-demo

logging.group:
  jooq:
    - org.jooq.Constants
    - org.jooq.tools.LoggerListener
  app:
    - org.febit.boot.demo.doggy

logging.level:
  app: info
  jooq: warn

app.auth:
  token-expire-seconds: 3600
